from typing import Dict, Any
import os
APP_NAME = "Thermal Printer"
APP_VERSION = ""  # no version yet - still in beta
CONFIG_FILENAME = "config.yaml"

# printer
DEFAULT_PRINTER_WIDTH = 384
DEFAULT_RFCOMM_CHANNEL = 1

# fonts
DEFAULT_FONT_SIZE = 24
DEFAULT_FONT_FAMILY = "DejaVu Sans Mono"
MIN_FONT_SIZE = 8
MAX_FONT_SIZE = 320

# text alignment
TEXT_ALIGN_LEFT = "left"
TEXT_ALIGN_CENTER = "center"
TEXT_ALIGN_RIGHT = "right"
DEFAULT_TEXT_ALIGN = TEXT_ALIGN_LEFT

# image processing
DEFAULT_BRIGHTNESS = 1.0
DEFAULT_CONTRAST = 1.0
DEFAULT_DITHER_MODE = "none"

DITHER_MODES = [
    "none",
    "floyd-steinberg",
    "ordered",
    "atkinson",
    "burkes",
    "sierra",
    "stucki",
]

ROTATION_OPTIONS = [0, 90, 180, 270]
DEFAULT_ROTATION = 0

DEFAULT_WINDOW_WIDTH = 800
DEFAULT_WINDOW_HEIGHT = 700
MIN_WINDOW_WIDTH = 600
MIN_WINDOW_HEIGHT = 500

UI_LABEL_FONT_SIZE = 14
UI_CONTROL_FONT_SIZE = 14
UI_BUTTON_FONT_SIZE = 14
UI_BUTTON_WIDTH = 100
UI_BUTTON_HEIGHT = 36
UI_SLIDER_WIDTH = 180
UI_SLIDER_HEIGHT = 20
UI_DROPDOWN_HEIGHT = 32

PREVIEW_WIDTH = 500
PREVIEW_HEIGHT = 400

PREVIEW_PAPER_WIDTH = 384
PREVIEW_MIN_SIDEBAR_WIDTH = 20
PREVIEW_PAPER_BORDER_WIDTH = 1
PREVIEW_SIDEBAR_COLOR_LIGHT = "gray85"
PREVIEW_SIDEBAR_COLOR_DARK = "gray25"
PREVIEW_MIN_SCALE = 0.5
PREVIEW_MAX_SCALE = 3.0
DEFAULT_PREVIEW_SCALE = 1.0
PREVIEW_PAPER_PADDING = 8
PREVIEW_FALLBACK_WIDTH = 400
PREVIEW_FALLBACK_HEIGHT = 200
PREVIEW_SCROLL_UNITS = 3
PREVIEW_PLACEHOLDER_FONT = "Arial"
PREVIEW_PLACEHOLDER_FONT_SIZE = 14
PREVIEW_PLACEHOLDER_TEXT = "Preview will appear here"
PREVIEW_PLACEHOLDER_COLOR = "gray50"

CALENDAR_CELL_WIDTH = 54
CALENDAR_CELL_HEIGHT = 28
CALENDAR_HEADER_HEIGHT = 32
CALENDAR_DAY_HEADER_HEIGHT = 24
CALENDAR_CELL_PADDING = 3
CALENDAR_DEFAULT_FONT_SIZE = 14
CALENDAR_GRID_COLUMNS = 7
CALENDAR_GRID_BORDER_WIDTH = 1
CALENDAR_WEEK_ROW_HEIGHT = 36
CALENDAR_WEEK_NOTE_AREA_HEIGHT = 48
CALENDAR_WEEK_BOTTOM_BORDER = 2
CALENDAR_WEEK_HEADER_TEXT_PADDING = 8
CALENDAR_WEEK_HEADER_Y_OFFSET = 4
CALENDAR_SUNDAY_FIRST = 6
CALENDAR_DAYS_IN_WEEK = 6

CALENDAR_MONTH_RIGHT_BORDER_PIXELS = 1
CALENDAR_MONTH_BOTTOM_BORDER_PIXELS = 1

LABEL_DEFAULT_DARKNESS = 1.5
LABEL_DEFAULT_LINE_SPACING = 1.2
LABEL_TEXT_FILL_BLACK = (0, 0, 0)
LABEL_ID_LENGTH = 8

CANVAS_MIN_SIZE_CHECK = 10
CANVAS_DRAG_MIN_POSITION = 0
CANVAS_DRAG_BOUNDARY_MARGIN = 10
CANVAS_AREA_LABEL_OFFSET_X = 15
CANVAS_AREA_LABEL_OFFSET_Y = 15
CANVAS_AREA_LABEL_FONT_SIZE = 10
CANVAS_AREA_LABEL_PADDING_X = 3
CANVAS_AREA_LABEL_PADDING_Y = 2
CANVAS_AREA_LABEL_BOLD = "bold"
CANVAS_LABEL_BG_COLOR = "#333333"
CANVAS_LABEL_Y_OFFSET_ABOVE = 16
CANVAS_LABEL_Y_OFFSET_BELOW = 4
CANVAS_LABEL_X_OFFSET = 2
CANVAS_AREA_BORDER_WIDTH = 2
CANVAS_AREA_BORDER_DASH = (4, 4)
CANVAS_MIN_FONT_SIZE = 8
CANVAS_DARKNESS_BOLD_THRESHOLD = 1.3
CANVAS_DARKNESS_BOLD_OFFSET = 1
CANVAS_REDRAW_DELAY_MS = 50
CANVAS_SCALE_THRESHOLD = 1.0
CANVAS_FALLBACK_IMAGE_SIZE = 100

# wayland grabs need delays or they fail mysteriously
WAYLAND_GNOME_GRAB_DELAY = 100
WAYLAND_KWIN_GRAB_DELAY = 50
WAYLAND_SWAY_GRAB_DELAY = 150
WAYLAND_WLROOTS_GRAB_DELAY = 150
WAYLAND_DEFAULT_GRAB_DELAY = 100

TEXT_RENDER_MAX_HEIGHT = 5000
TEXT_RENDER_EMPTY_HEIGHT = 10
TEXT_RENDER_LEFT_PADDING = 10
TEXT_RENDER_RIGHT_PADDING = 20
TEXT_RENDER_LINE_SPACING_MULTIPLIER = 1.2
TEXT_RENDER_CHAR_WIDTH_MULTIPLIER = 0.5
TEXT_RENDER_BG_WHITE = (255, 255, 255)
TEXT_RENDER_TRIM_PADDING = 10
TEXT_RENDER_TRIM_DIFF_SCALE = 2.0
TEXT_RENDER_PREVIEW_MAX_WIDTH = 400
TEXT_RENDER_PREVIEW_MAX_HEIGHT = 300

UNICODE_CHAR_WIDTH_MULTIPLIER = 0.6
UNICODE_DEFAULT_FONT_SIZE = 24

FILE_DIALOG_TIMEOUT = 300
CLIPBOARD_TIMEOUT = 2

VALIDATOR_MIN_BRIGHTNESS = 0.0
VALIDATOR_MAX_BRIGHTNESS = 2.0
VALIDATOR_MIN_CONTRAST = 0.0
VALIDATOR_MAX_CONTRAST = 2.0
VALIDATOR_MIN_PRINTER_WIDTH = 1
VALIDATOR_MAX_PRINTER_WIDTH = 4096
VALIDATOR_MIN_RFCOMM_CHANNEL = 1
VALIDATOR_MAX_RFCOMM_CHANNEL = 30

MAC_ADDRESS_BYTE_COUNT = 12
MAC_ADDRESS_PAIR_SIZE = 2
MAC_ADDRESS_PAIR_STEP = 2

WIDGET_CHANGE_DELAY_MS = 10
WIDGET_SELECT_START_INDEX = 0
WIDGET_SELECT_END_INDEX = "end"
TEXTBOX_SELECT_START = "1.0"
TEXTBOX_SELECT_END = "end-1c"

GUI_WINDOW_CENTER_DIVISOR = 2
GUI_GRID_COLUMN_MAIN = 0
GUI_GRID_ROW_STATUS = 2
GUI_GRID_ROW_CONNECTION = 0
GUI_GRID_ROW_TABS = 1
GUI_GRID_WEIGHT = 1
GUI_PADDING_X = 10
GUI_PADDING_Y_TOP = 10
GUI_PADDING_Y_SMALL = 5
GUI_PADDING_Y_MEDIUM = 2
GUI_PADDING_X_SMALL = 2
GUI_PADDING_Y_LARGE = 4
GUI_TAB_BUTTON_FONT_SIZE = 14
GUI_TAB_BUTTON_HEIGHT = 40
GUI_TAB_BUTTON_CORNER_RADIUS = 8
GUI_TAB_BUTTON_WIDTH = 100

SCROLLBAR_HEIGHT = 12
SCROLLBAR_WIDTH = 12

CANVAS_SCROLL_REGION_ORIGIN = 0
CANVAS_MOUSE_WHEEL_UP = -1
CANVAS_MOUSE_WHEEL_DOWN = 1

AFTER_IMMEDIATE = 0

APPEARANCE_MODES = ["System", "Light", "Dark"]
DEFAULT_APPEARANCE = "System"

COLOR_THEMES = ["blue", "green", "dark-blue"]
DEFAULT_COLOR_THEME = "blue"

DEFAULT_COMMAND_DELAY = 0.5
DEFAULT_SCAN_TIMEOUT = 10
SETTINGS_SAVE_DELAY = 1.0
WINDOW_RESIZE_SAVE_DELAY = 0.5

BLUETOOTH_COMMAND_TIMEOUT = 5
BLUETOOTH_SCAN_POLL_INTERVAL = 0.5
BLUETOOTH_PAIRING_RETRY_DELAY = 0.3
BLUETOOTH_SCAN_STOP_TIMEOUT = 2
RECONNECT_MAX_ATTEMPTS = 3
RECONNECT_BACKOFF_BASE = 2
RECONNECT_BACKOFF_CAP_SECONDS = 8

PRINT_PROGRESS_INIT = 0
PRINT_PROGRESS_START = 10
PRINT_PROGRESS_IMAGE = 20
PRINT_PROGRESS_FINISH = 95
PRINT_PROGRESS_COMPLETE = 100
PRINT_PROGRESS_IMAGE_RANGE = 70

PRINT_COMMAND_DELAY_MULTIPLIER = 0.5

DEFAULT_FEED_LINES_BEFORE = 0
DEFAULT_FEED_LINES_AFTER = 3
MIN_FEED_LINES = 0
MAX_FEED_LINES = 20

PRINTER_WIDTH_BITS_PER_BYTE = 8
PROTOCOL_STATUS_RESPONSE_LENGTH = 38
PROTOCOL_LITTLE_ENDIAN_BYTE_COUNT = 2
PROTOCOL_MODULO = 256

DEFAULT_CHUNK_SIZE = 4096
KB_DIVISOR = 1024

DATE_FORMATS = [
    "%Y-%m-%d %H:%M",
    "%Y-%m-%d",
    "%d/%m/%Y %H:%M",
    "%d/%m/%Y",
    "%m/%d/%Y %H:%M",
    "%m/%d/%Y",
    "%B %d, %Y",
    "%b %d, %Y %H:%M",
]
DEFAULT_DATE_FORMAT = "%Y-%m-%d %H:%M"

LINUX_FONT_PATHS = [
    "/usr/share/fonts",
    "/usr/local/share/fonts",
    os.path.expanduser("~/.fonts"),
    os.path.expanduser("~/.local/share/fonts"),
]

PREFERRED_FONTS = [
    "DejaVu Sans Mono",
    "Liberation Mono",
    "Noto Sans Mono",
    "Ubuntu Mono",
    "Fira Mono",
    "Source Code Pro",
    "Droid Sans Mono",
    "Inconsolata",
    "Courier New",
    "FreeMono",
    "Nimbus Mono L",
    "monospace",
]

FALLBACK_FONTS = [
    "Courier New",
    "Courier",
    "FreeMono",
    "DejaVu Sans Mono",
    "Liberation Mono",
]

# default unicode font (can be overridden in settings)
DEFAULT_UNICODE_FONT = "Catrinity"

# recommended unicode fonts (highlighted in settings)
RECOMMENDED_UNICODE_FONTS = [
    "Catrinity",
    "Code2000",
    "Everson",
    "Quivira",
    "DejaVu Sans",
    "Stix",
    "Noto",
]

UNICODE_FALLBACK_FONTS = [
    "Catrinity",
    "Noto Sans Math",
    "STIX Two Math",
    "Symbola",
    "Noto Sans Symbols",
    "Noto Sans Symbols 2",
    "DejaVu Sans",
    "DejaVu Serif",
    "Noto Sans",
    "FreeSerif",
    "FreeSans",
]

SUPPORTED_IMAGE_FORMATS = [
    ("All image files", "*.png *.jpg *.jpeg *.bmp *.gif"),
    ("PNG files", "*.png"),
    ("JPEG files", "*.jpg *.jpeg"),
    ("BMP files", "*.bmp"),
    ("GIF files", "*.gif"),
    ("All files", "*.*"),
]

SUPPORTED_TEXT_FORMATS = [
    ("Text files", "*.txt"),
    ("All files", "*.*"),
]

DIALOG_GALLERY_WIDTH = 900
DIALOG_GALLERY_HEIGHT = 700
DIALOG_GALLERY_MIN_WIDTH = 600
DIALOG_GALLERY_MIN_HEIGHT = 400

DIALOG_SCANNER_WIDTH = 450
DIALOG_SCANNER_HEIGHT = 420

DIALOG_CALENDAR_WIDTH = 420
DIALOG_CALENDAR_HEIGHT = 540

DIALOG_MATH_SYMBOLS_WIDTH = 650
DIALOG_MATH_SYMBOLS_HEIGHT = 700

DIALOG_FONT_INSTALL_WIDTH = 500
DIALOG_FONT_INSTALL_HEIGHT = 350

DIALOG_MESSAGE_MIN_WIDTH = 300
DIALOG_MESSAGE_MIN_HEIGHT = 150

DIALOG_BUTTON_WIDTH = 100
DIALOG_BUTTON_HEIGHT = 36
DIALOG_BUTTON_SMALL_WIDTH = 80
DIALOG_BUTTON_LARGE_WIDTH = 120

DIALOG_PADDING = 20
DIALOG_PADDING_SMALL = 10
DIALOG_PADDING_LARGE = 30

CANVAS_AREA_BORDER_NORMAL = "#666666"
CANVAS_AREA_BORDER_HOVER = "#4488FF"
CANVAS_AREA_BORDER_SELECTED = "#0066CC"
CANVAS_AREA_FILL_NORMAL = "#DDDDDD"
CANVAS_AREA_FILL_SELECTED = "#CCE5FF"
CANVAS_AREA_FILL_OPACITY = 0.3

CANVAS_BG_LIGHT = "#FFFFFF"
CANVAS_BG_DARK = "#2B2B2B"
CANVAS_PANED_BG_LIGHT = "#DBDBDB"
CANVAS_PANED_BG_DARK = "#3B3B3B"

GALLERY_THUMBNAIL_BG = "#FFFFFF"
GALLERY_THUMBNAIL_BORDER = "#CCCCCC"
GALLERY_THUMBNAIL_TEXT = "#333333"
GALLERY_THUMBNAIL_LABEL_BG = "#F0F0F0"
GALLERY_THUMBNAIL_LABEL_TEXT = "#666666"
GALLERY_ERROR_THUMBNAIL_BG = "#F5F5F5"
GALLERY_ERROR_THUMBNAIL_BORDER = "#888888"
GALLERY_PCFG_THUMBNAIL_BG = "#E0E0E0"

ICON_COLOR_ERROR = "#e74c3c"
ICON_COLOR_WARNING = "#f39c12"
ICON_COLOR_INFO = "#3498db"
ICON_COLOR_SUCCESS = "#27ae60"
ICON_COLOR_QUESTION = "#9b59b6"

BUTTON_DELETE_FG = ("#CC4444", "#AA2222")
BUTTON_DELETE_HOVER = ("#AA2222", "#881111")
BUTTON_PRINT_FG = ("green", "#00AA00")
BUTTON_PRINT_HOVER = ("darkgreen", "#008800")
BUTTON_CONNECT_FG = ("green", "#004400")
BUTTON_SCAN_FG = ("blue", "#0066CC")

DEBOUNCE_PREVIEW_UPDATE_MS = 500
DEBOUNCE_SEARCH_MS = 200
DEBOUNCE_TEXT_UPDATE_MS = 200
DEBOUNCE_UNICODE_CHECK_MS = 300
DEBOUNCE_RESIZE_MS = 50
DEBOUNCE_GRID_RESIZE_MS = 100

FEEDBACK_COPY_RESET_MS = 1500
FEEDBACK_POPUP_DELAY_MS = 100
FEEDBACK_FONT_SWITCH_DELAY_MS = 100

MODAL_CENTER_DELAY_MS = 10
MODAL_POSITION_DELAY_MS = 50
MODAL_GRAB_DELAY_MS = 10

SCROLL_BIND_DELAY_MS = 50

DOUBLE_CLICK_DELAY_MS = 250

STATUS_BT_CHECK_INTERVAL_MS = 5000

SCAN_START_DELAY_MS = 150

DARKNESS_MIN = 0.3
DARKNESS_MAX = 3.0
DARKNESS_DEFAULT = 1.5

BRIGHTNESS_MIN = 0.0
BRIGHTNESS_MAX = 2.0

IMAGE_MAX_DIMENSION = 4096
IMAGE_MIN_DIMENSION = 1

THUMBNAIL_SIZE_SMALL = 100
THUMBNAIL_SIZE_MEDIUM = 150
THUMBNAIL_SIZE_LARGE = 200

GALLERY_THUMBNAIL_DEFAULT_SIZE = 150

FONT_SIZE_SMALL = 12
FONT_SIZE_NORMAL = 14
FONT_SIZE_LARGE = 16
FONT_SIZE_XLARGE = 18
FONT_SIZE_TITLE = 20
FONT_SIZE_HEADER = 24

FONT_WEIGHT_NORMAL = "normal"
FONT_WEIGHT_BOLD = "bold"

FONT_MONOSPACE_SIZE = 13


def get_default_config() -> Dict[str, Any]:
    return {
        "printer": {
            "mac_address": "",
            "device_name": "",
            "width": DEFAULT_PRINTER_WIDTH,
            "rfcomm_channel": DEFAULT_RFCOMM_CHANNEL,
        },
        "text": {
            "font_family": DEFAULT_FONT_FAMILY,
            "font_size": DEFAULT_FONT_SIZE,
            "alignment": DEFAULT_TEXT_ALIGN,
            "bold": False,
            "italic": False,
            "darkness": 1.0,
            "add_date": False,
            "date_format": DEFAULT_DATE_FORMAT,
        },
        "image": {
            "brightness": DEFAULT_BRIGHTNESS,
            "contrast": DEFAULT_CONTRAST,
            "dither_mode": DEFAULT_DITHER_MODE,
            "rotation": DEFAULT_ROTATION,
            "invert": False,
            "auto_resize": True,
        },
        "gui": {
            "window_width": DEFAULT_WINDOW_WIDTH,
            "window_height": DEFAULT_WINDOW_HEIGHT,
            "window_x": None,
            "window_y": None,
            "appearance_mode": DEFAULT_APPEARANCE,
            "color_theme": DEFAULT_COLOR_THEME,
            "last_tab": "Text",
            "gallery_thumbnail_size": "Medium",
            "preview_scale": DEFAULT_PREVIEW_SCALE,
        },
        "timing": {
            "command_delay": DEFAULT_COMMAND_DELAY,
            "scan_timeout": DEFAULT_SCAN_TIMEOUT,
        },
        "printing": {
            "feed_lines_before": DEFAULT_FEED_LINES_BEFORE,
            "feed_lines_after": DEFAULT_FEED_LINES_AFTER,
        },
        "banner": {
            "font_family": DEFAULT_FONT_FAMILY,
            "font_size": 72,
            "alignment": DEFAULT_TEXT_ALIGN,
            "bold": False,
            "italic": False,
            "darkness": 1.5,
            "add_date": False,
            "date_format": DEFAULT_DATE_FORMAT,
        },
        "label": {
            "darkness": 1.5,
            "last_template_dir": "",
        },
        "unicode": {
            "show_font_switch_popup": True,
            "preferred_font": DEFAULT_UNICODE_FONT,
        },
    }
